export const eventData = [
    {
        listingName: "Binance Meetup Abuja",
        aboutListing: "An event for Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequuntur explicabo iste tempora esse quae corrupti.",
        aboutListing: "An event for aimed at bringing together Crypto-minded people to look into certain topics and network in fostering the growth...",
        venue: "Transcorp Hilton, Abuja, Nigeria",
        startDate: "22/08/2022",
        endingDate: "22/08/2022",
        startTime: "10:00am",
        endingTime: "1:30pm",
    },
    {
        listingName: "Facebook Developers Meetup",
        aboutListing: "An event aimed at bringing Developers to Teach, Learn and Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, dolorum?",
        venue: "ZOOM (Online)",
        startDate: "05/09/2022",
        endingDate: "05/09/2022",
        startTime: "09:30am",
        endingTime: "12:30pm",
    },
    {
        listingName: "Major League Hacking (MLH) Meetup",
        aboutListing: "An event aimed at bringing Developers to Teach, Learn and Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, dolorum?",
        venue: "Eko Hotel, Lagos State, Nigeria. ",
        startDate: "05/10/2022",
        endingDate: "08/10/2022",
        startTime: "10:00am",
        endingTime: "1:30pm",
    },
    {
        listingName: "Major League Hacking MLH Meetup",
        aboutListing: "An event aimed at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, dolorum?",
        venue: "PortHarcout Township Hall, Rivers State, Nigeria. ",
        startingDate: "02/02/2022",
        endingDate: "02/02/2022",
        startingTime: "10:00am",
        endingTime: "1:30pm",
    },

]