export const eventData = [
    {
        listingName: "Binance Meetup Asaba",
        aboutListing: "An event for Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequuntur explicabo iste tempora esse quae corrupti.",
        aboutListing: "An event for aimed at bringing together Crypto-minded people to look into certain topics and network in fostering the growth...",
        venue: "Asaba Township Hall, Nigeria",
        startDate: "02/02/2022",
        endingDate: "02/02/2022",
        startTime: "10:00am",
        endingTime: "1:30pm",
    },
    {
        listingName: "Facebook Developers Meetup",
        aboutListing: "An event aimed at bringing Developers to Teach, Learn and Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, dolorum?",
        venue: "ZOOM (Online)",
        startDate: "02/02/2022",
        endingDate: "02/02/2022",
        startTime: "10:00am",
        endingTime: "1:30pm",
    },
    {
        listingName: "Major League Hacking (MLH) Meetup",
        aboutListing: "An event aimed at bringing Developers to Teach, Learn and Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, dolorum?",
        venue: "Maiduguri, Borno State, Nigeria. ",
        startDate: "02/02/2022",
        endingDate: "02/02/2022",
        startTime: "10:00am",
        endingTime: "1:30pm",
    },
    {
        listingName: "Major League Hacking MLH Meetup",
        aboutListing: "An event aimed at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, dolorum?",
        venue: "Maiduguri, Borno State, Nigeria. ",
        startDate: "02/02/2022",
        endingDate: "02/02/2022",
        startTime: "10:00am",
        endingTime: "1:30pm",
    },

]